name: Environment Validation

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/ci.yml
